migrate gfiPie to V3
Dataport/MasterportalAddons pull request #4
Opened 2024-11-27 10:25 UTC by FinnDarge

The addon gfiPie has been migrated to Masterportal Version 3.x and with that some changes to the folder structure have been made.

To test the gfiPie use the following portalconfig where the layer "Trinkwasser" was configured to work with the addon.

[gfiPieTrinkwasser.zip](https://github.com/user-attachments/files/17932779/gfiPieTrinkwasser.zip)

2024-12-03 16:06 UTC, jedi-of-the-sea requested changes
🏓 @FinnDarge Bin erstmal durch.
Mir ist aufgefallen, dass ich manchmal mehrere Male auf die Punkte klicken musste, damit etwas passiert, aber ich glaube das wäre beim normalen GFI nicht anders und ist dem geschuldet, dass es sich um Punkte handelt, die nicht immer gut getroffen werden.

2024-12-05 06:51 UTC, FinnDarge commented on masterportalVersion2/gfiThemes/gfiPie/components/GfiPie.vue
> +            return typeof d === "undefined" ? true : d;
Erledigt

2024-12-05 06:52 UTC, FinnDarge commented on masterportalVersion2/gfiThemes/gfiPie/components/GfiPie.vue
> +            return typeof d === "undefined" ? true : d;
Erledigt

2024-12-05 06:52 UTC, FinnDarge commented on masterportalVersion2/gfiThemes/gfiPie/components/GfiPie.vue
> +            }
👍

2024-12-05 06:52 UTC, FinnDarge commented on masterportalVersion2/gfiThemes/gfiPie/components/GfiPie.vue
> +            }
👍

2024-12-05 06:52 UTC, FinnDarge commented on masterportalVersion2/gfiThemes/gfiPie/components/GfiPie.vue
> +            return this.parseData(parser);
👍

2024-12-05 06:52 UTC, FinnDarge commented on masterportalVersion2/gfiThemes/gfiPie/components/GfiPie.vue
> +                    }
👍

2024-12-05 06:52 UTC, FinnDarge commented on masterportalVersion2/gfiThemes/gfiPie/components/GfiPie.vue
> +                            }
👍

2024-12-05 06:53 UTC, FinnDarge commented on masterportalVersion2/gfiThemes/gfiPie/README.md
Guter Einwand, habe ich zur Readme hinzugefügt.

2024-12-05 06:54 UTC, FinnDarge commented
🏓 @jedi-of-the-sea Ich habe mich jetzt nochmal nach deinem Input mit den Funktionen beschäftigt, diese refaktorisiert und kommentiert wo notwendig. Schau gerne drüber, ob es so passt.

2024-12-09 14:58 UTC, jedi-of-the-sea commented
🚀 @FinnDarge

2024-12-10 07:45 UTC, merged